"""PT report writer.

Produces:
  * normalized-recon.json
  * owasp-mapping.json
  * pt-test-plan.json
  * attack-vectors.json
  * report.md   - Markdown PT plan
  * report.html - Self-contained HTML dashboard (browser-friendly,
                  print/PDF-ready). Reuses the recon's CSS/JS so the
                  look-and-feel matches the Phase-1 HTML report.
"""
from __future__ import annotations

import json
from pathlib import Path

from ..report_writer import _HTML_CSS, _HTML_JS, _html_escape, _shorten
from .schema import (
    AttackVector,
    NormalizedRecon,
    OwaspMappingItem,
    PTAssessmentSummary,
    PTPlan,
    PTTestAssignment,
    Priority,
)


# ---------------------------------------------------------------------------
# Markdown helpers
# ---------------------------------------------------------------------------

def _bullet(items: list[str]) -> str:
    return "\n".join(f"- {x}" for x in items) if items else "- _none_"


def _safe(items: list[str]) -> list[str]:
    return [str(i) for i in items if isinstance(i, str) and i.strip()]


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------

def build_markdown(
    recon: NormalizedRecon,
    summary: PTAssessmentSummary,
    mapping: list[OwaspMappingItem],
    assignments: list[PTTestAssignment],
    vectors: list[AttackVector],
) -> str:
    """Render the PT plan as Markdown."""
    caps = recon.capabilities
    lines: list[str] = []

    # ---- Header ----
    lines.append("# AI Agent Penetration Testing Plan")
    lines.append("")
    lines.append("_Generated by ai-agents-recon Phase 2-4 (deterministic + CrewAI agents)._")
    lines.append("")

    # ---- Target Summary ----
    lines.append("## Target Summary")
    lines.append("")
    lines.append(f"- **Target name**: `{summary.target_name}`")
    lines.append(f"- **Target type**: `{summary.target_type}`")
    lines.append(f"- **Overall risk**: **{summary.overall_risk}**")
    lines.append(
        "- **Key capabilities**: "
        + ", ".join(
            f"`{flag}`"
            for flag, value in (
                ("has_tools", caps.has_tools),
                ("has_mcp", caps.has_mcp),
                ("has_memory", caps.has_memory),
                ("has_rag", caps.has_rag),
                ("can_execute_code", caps.can_execute_code),
                ("can_call_external_apis", caps.can_call_external_apis),
                ("can_modify_data", caps.can_modify_data),
                ("multi_agent", caps.multi_agent),
                ("has_human_approval", caps.has_human_approval),
            )
            if value
        )
        or "_none confirmed_"
    )
    lines.append(f"- **Permission scope**: `{caps.permission_scope}`")
    lines.append(f"- **Identity model**: `{caps.identity_model}`")
    if summary.top_focus_areas:
        lines.append("- **Top focus areas**:")
        for f in summary.top_focus_areas:
            lines.append(f"  - {f}")
    if summary.reason:
        lines.append(f"- **Reason**: {summary.reason}")
    lines.append("")

    # ---- OWASP Mapping ----
    lines.append("## OWASP Agentic AI Mapping")
    lines.append("")
    lines.append(
        "_Reference: https://www.promptfoo.dev/docs/red-team/owasp-agentic-ai/_"
    )
    lines.append("")
    lines.append("| ID | Name | Applicable | Priority | Confidence | Score |")
    lines.append("|---|---|---|---|---|---|")
    for m in mapping:
        applicable = "Yes" if m.applicable else "-"
        lines.append(
            f"| {m.owasp_id} | {m.name} | {applicable} | {m.priority} | "
            f"{m.confidence:.2f} | {m.score_breakdown.total} |"
        )
    lines.append("")

    for m in mapping:
        if not m.applicable:
            continue
        lines.append(f"### {m.owasp_id} - {m.name}")
        lines.append("")
        lines.append(f"- **Priority**: {m.priority}  -  **Confidence**: {m.confidence:.2f}")
        lines.append(
            f"- **Score**: {m.score_breakdown.total} "
            f"(impact={m.score_breakdown.impact}, "
            f"exploitability={m.score_breakdown.exploitability}, "
            f"exposure={m.score_breakdown.exposure}, "
            f"privilege={m.score_breakdown.privilege}, "
            f"autonomy={m.score_breakdown.autonomy}, "
            f"approval_control=-{m.score_breakdown.approval_control})"
        )
        lines.append(f"- **Rationale**: {m.rationale}")
        lines.append("- **Matched recon signals**:")
        lines.append(_bullet(_safe(m.matched_recon_signals)))
        lines.append("- **Recommended test focus**:")
        lines.append(_bullet(_safe(m.recommended_test_focus)))
        lines.append("")

    # ---- Prioritized Attack Vectors ----
    lines.append("## Prioritized Attack Vectors")
    lines.append("")
    if not vectors:
        lines.append("_No attack vectors generated (no applicable categories)._")
        lines.append("")
    else:
        by_asi: dict[str, list[AttackVector]] = {}
        for v in vectors:
            by_asi.setdefault(v.owasp_id, []).append(v)
        order = [m.owasp_id for m in mapping if m.applicable]
        for owasp_id in order:
            vs = by_asi.get(owasp_id, [])
            if not vs:
                continue
            lines.append(f"### {owasp_id} vectors")
            lines.append("")
            for v in vs:
                lines.append(f"#### `{v.id}` {v.title}")
                lines.append("")
                lines.append(f"- **Priority**: {v.priority}")
                lines.append(f"- **OWASP**: {v.owasp_id}")
                lines.append(f"- **Objective**: {v.objective}")
                if v.recon_basis:
                    lines.append("- **Recon basis**:")
                    lines.append(_bullet(_safe(v.recon_basis)))
                lines.append(f"- **Attack scenario**: {v.attack_scenario}")
                if v.preconditions:
                    lines.append("- **Preconditions**:")
                    lines.append(_bullet(_safe(v.preconditions)))
                if v.test_steps:
                    lines.append("- **Test steps**:")
                    lines.append(_bullet(_safe(v.test_steps)))
                if v.safe_payload_examples:
                    lines.append("- **Safe payload examples**:")
                    lines.append(
                        "\n".join(f"  - `{p}`" for p in _safe(v.safe_payload_examples))
                    )
                lines.append(f"- **Expected secure behavior**: {v.expected_secure_behavior}")
                lines.append(f"- **Vulnerable behavior**: {v.vulnerable_behavior}")
                if v.evidence_to_collect:
                    lines.append("- **Evidence to collect**:")
                    lines.append(_bullet(_safe(v.evidence_to_collect)))
                lines.append(f"- **Risk if successful**: {v.risk_if_successful}")
                if v.recommended_controls:
                    lines.append("- **Recommended controls**:")
                    lines.append(_bullet(_safe(v.recommended_controls)))
                lines.append(
                    f"- **Execution mode**: `{v.execution_mode}`  -  "
                    f"**Destructive**: `{v.destructive}`"
                )
                lines.append("")

    # ---- Execution Notes ----
    lines.append("## Execution Notes")
    lines.append("")
    lines.append(
        "- **Scope**: Only the target identified above, only the capabilities listed in "
        "this report, and only in the engagement-approved environment."
    )
    lines.append(
        "- **Safe testing rules**: Every vector here is non-destructive. Use only the "
        "marker `PT_TEST_TOKEN_DO_NOT_EXECUTE`, safe commands (`whoami`, `hostname`), "
        "test recipients, and dry-run modes. Do NOT escalate beyond the documented steps."
    )
    lines.append(
        "- **Required approvals**: Confirm written authorization to assess the target "
        "before execution."
    )
    lines.append(
        "- **Logging and evidence**: Capture full request/response bodies, tool-call "
        "traces, authorization decisions, and timestamps. Preserve session ids."
    )
    lines.append(
        "- **Backout / rollback**: For data-modification vectors, use isolated test "
        "records only and restore state immediately after each test."
    )
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------

_PRIORITY_CLASS: dict[Priority, str] = {
    "Critical": "sev-critical",
    "High": "sev-high",
    "Medium": "sev-medium",
    "Low": "sev-low",
    "Informational": "sev-info",
}

# PT-specific additions on top of the recon's CSS (criticals + vector cards).
_PT_EXTRA_CSS = """
.sev-critical {
  background: rgba(244,63,94,.18); color: #fb7185;
  border: 1px solid rgba(244,63,94,.40);
}
.risk-card.sev-critical { border-left-color: #fb7185; }
.vector-card {
  background: var(--panel-2); border: 1px solid var(--border);
  border-left: 4px solid var(--info);
  border-radius: 10px; padding: 14px 16px; margin-bottom: 12px;
}
.vector-card.sev-critical { border-left-color: #fb7185; }
.vector-card.sev-high     { border-left-color: var(--high); }
.vector-card.sev-medium   { border-left-color: var(--medium); }
.vector-card.sev-low      { border-left-color: var(--low); }
.vector-card.sev-info     { border-left-color: var(--info); }
.vector-header {
  display: flex; align-items: center; gap: 10px;
  margin-bottom: 8px; flex-wrap: wrap;
}
.vector-header h4 { margin: 0; font-size: 14px; flex: 1; min-width: 0; }
.vector-id {
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: 12px; color: var(--muted);
}
.vector-body { display: grid; grid-template-columns: 1.2fr 1fr; gap: 18px; }
.vector-body h5 {
  margin: 0 0 4px 0; font-size: 11px; text-transform: uppercase;
  letter-spacing: .05em; color: var(--muted);
}
.vector-body p, .vector-body ul { margin: 0 0 10px 0; }
.vector-body ul { padding-left: 18px; }
.vector-body code, .vector-body .mono-list {
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: 12px;
}
.vector-payload {
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: 12px;
  background: var(--bg); border: 1px solid var(--border);
  padding: 2px 8px; border-radius: 4px;
  display: inline-block; margin: 2px 4px 2px 0;
}
.category-block { margin-bottom: 22px; }
.category-block h3 {
  display: flex; align-items: center; gap: 10px;
  margin: 10px 0 10px 0; font-size: 14px;
}
.score-detail {
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: 11px; color: var(--muted); margin-top: 4px;
}
.assignment-row td:first-child { font-weight: 600; }
.specialist {
  font-size: 12px; color: var(--accent); font-weight: 500;
}
@media (max-width: 720px) {
  .vector-body { grid-template-columns: 1fr; }
}
"""


def _priority_class(p: str) -> str:
    return _PRIORITY_CLASS.get(p, "sev-info")  # type: ignore[arg-type]


def _bullets_html(items: list[str]) -> str:
    items = _safe(items)
    if not items:
        return '<p class="muted small">None.</p>'
    return "<ul>" + "".join(f"<li>{_html_escape(x)}</li>" for x in items) + "</ul>"


def _render_owasp_table(mapping: list[OwaspMappingItem]) -> str:
    rows: list[str] = []
    for m in mapping:
        applicable_pill = (
            "<span class='pill conf-high'>yes</span>"
            if m.applicable
            else "<span class='pill conf-uncertain'>no</span>"
        )
        priority_pill = (
            f"<span class='pill {_priority_class(m.priority)}'>"
            f"{_html_escape(m.priority)}</span>"
        )
        rows.append(
            "<tr>"
            f"<td class='mono small'>{_html_escape(m.owasp_id)}</td>"
            f"<td>{_html_escape(m.name)}</td>"
            f"<td>{applicable_pill}</td>"
            f"<td>{priority_pill}</td>"
            f"<td class='mono small'>{m.confidence:.2f}</td>"
            f"<td class='mono small'>{m.score_breakdown.total}</td>"
            "</tr>"
        )
    return (
        "<div class='scroll-wrap'><table class='data-table'>"
        "<thead><tr>"
        "<th>ID</th><th>Name</th><th>Applicable</th>"
        "<th>Priority</th><th>Confidence</th><th>Score</th>"
        "</tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table></div>"
    )


def _render_owasp_cards(mapping: list[OwaspMappingItem]) -> str:
    cards: list[str] = []
    for m in mapping:
        if not m.applicable:
            continue
        sev = _priority_class(m.priority)
        sb = m.score_breakdown
        cards.append(
            f"<article class='risk-card {sev}' id='owasp-{_html_escape(m.owasp_id.lower())}'>"
            "<header class='risk-header'>"
            f"<span class='pill {sev}'>{_html_escape(m.priority)}</span>"
            f"<h3>{_html_escape(m.owasp_id)} &middot; {_html_escape(m.name)}</h3>"
            f"<span class='pill conf-medium'>conf: {m.confidence:.2f}</span>"
            "</header>"
            f"<p class='risk-desc'>{_html_escape(m.rationale)}</p>"
            "<div class='risk-grid'>"
            "<div>"
            "<h4>Matched recon signals</h4>"
            f"{_bullets_html(m.matched_recon_signals)}"
            "</div>"
            "<div>"
            "<h4>Recommended test focus</h4>"
            f"{_bullets_html(m.recommended_test_focus)}"
            "<h4>Score breakdown</h4>"
            f"<p class='score-detail'>total={sb.total} "
            f"(impact={sb.impact}, exploit={sb.exploitability}, "
            f"exposure={sb.exposure}, privilege={sb.privilege}, "
            f"autonomy={sb.autonomy}, approval=-{sb.approval_control})</p>"
            "</div>"
            "</div></article>"
        )
    return "\n".join(cards) if cards else '<p class="muted">No applicable categories.</p>'


def _render_vector_card(v: AttackVector) -> str:
    sev = _priority_class(v.priority)
    payloads_html = (
        "".join(
            f"<code class='vector-payload'>{_html_escape(p)}</code>"
            for p in _safe(v.safe_payload_examples)
        )
        or '<span class="muted small">no payloads</span>'
    )
    return (
        f"<article class='vector-card {sev}'>"
        "<header class='vector-header'>"
        f"<span class='pill {sev}'>{_html_escape(v.priority)}</span>"
        f"<h4>{_html_escape(v.title)}</h4>"
        f"<span class='vector-id'>{_html_escape(v.id)}</span>"
        "</header>"
        f"<p class='small'>{_html_escape(v.objective)}</p>"
        "<details>"
        "<summary class='small muted'>Show full vector</summary>"
        "<div class='vector-body'>"
        "<div>"
        "<h5>Attack scenario</h5>"
        f"<p>{_html_escape(v.attack_scenario)}</p>"
        "<h5>Test steps</h5>"
        f"{_bullets_html(v.test_steps)}"
        "<h5>Safe payload examples</h5>"
        f"<p>{payloads_html}</p>"
        "<h5>Recon basis</h5>"
        f"{_bullets_html(v.recon_basis)}"
        "</div>"
        "<div>"
        "<h5>Expected secure behavior</h5>"
        f"<p>{_html_escape(v.expected_secure_behavior)}</p>"
        "<h5>Vulnerable behavior</h5>"
        f"<p>{_html_escape(v.vulnerable_behavior)}</p>"
        "<h5>Evidence to collect</h5>"
        f"{_bullets_html(v.evidence_to_collect)}"
        "<h5>Risk if successful</h5>"
        f"<p>{_html_escape(v.risk_if_successful)}</p>"
        "<h5>Recommended controls</h5>"
        f"{_bullets_html(v.recommended_controls)}"
        f"<p class='small muted'>execution: <code>{_html_escape(v.execution_mode)}</code> "
        f"&middot; destructive: <code>{str(v.destructive).lower()}</code></p>"
        "</div>"
        "</div>"
        "</details>"
        "</article>"
    )


def _render_vectors_section(
    mapping: list[OwaspMappingItem], vectors: list[AttackVector]
) -> str:
    if not vectors:
        return '<p class="muted">No attack vectors generated.</p>'

    by_asi: dict[str, list[AttackVector]] = {}
    for v in vectors:
        by_asi.setdefault(v.owasp_id, []).append(v)
    # Preserve mapping order; only show applicable categories with vectors.
    order = [m for m in mapping if m.applicable and m.owasp_id in by_asi]

    blocks: list[str] = []
    blocks.append(
        "<div class='table-tools'>"
        "<input id='vectorFilter' type='search' "
        "placeholder='Filter by ID, title, or scenario...' "
        "aria-label='Filter vectors'>"
        "<span id='vectorFilterCount' class='muted small'></span>"
        "</div>"
    )
    for m in order:
        sev = _priority_class(m.priority)
        vector_cards = "".join(_render_vector_card(v) for v in by_asi[m.owasp_id])
        # Wrap each block so the filter JS can show/hide it row-by-row.
        blocks.append(
            f"<div class='category-block' data-asi='{_html_escape(m.owasp_id)}'>"
            f"<h3><span class='pill {sev}'>{_html_escape(m.priority)}</span> "
            f"<span class='mono small'>{_html_escape(m.owasp_id)}</span> "
            f"&middot; {_html_escape(m.name)} "
            f"<span class='muted small'>({len(by_asi[m.owasp_id])} vector"
            f"{'s' if len(by_asi[m.owasp_id]) != 1 else ''})</span></h3>"
            f"<div class='vector-list'>{vector_cards}</div>"
            "</div>"
        )
    return "".join(blocks)


def _render_assignments(assignments: list[PTTestAssignment]) -> str:
    if not assignments:
        return '<p class="muted">No specialist assignments.</p>'
    rows: list[str] = []
    for a in assignments:
        sev = _priority_class(a.priority)
        vector_ids = (
            ", ".join(_html_escape(v) for v in a.vector_ids)
            if a.vector_ids
            else "<span class='muted small'>-</span>"
        )
        rows.append(
            "<tr class='assignment-row'>"
            f"<td class='mono small'>{_html_escape(a.owasp_id)}</td>"
            f"<td>{_html_escape(a.owasp_name)}</td>"
            f"<td><span class='pill {sev}'>{_html_escape(a.priority)}</span></td>"
            f"<td class='mono small'>{a.confidence:.2f}</td>"
            f"<td class='specialist'>{_html_escape(a.specialist)}</td>"
            f"<td class='mono small'>{vector_ids}</td>"
            "</tr>"
        )
    return (
        "<div class='scroll-wrap'><table class='data-table'>"
        "<thead><tr>"
        "<th>ID</th><th>Category</th><th>Priority</th>"
        "<th>Confidence</th><th>Specialist</th><th>Vector IDs</th>"
        "</tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table></div>"
    )


_PT_JS = """
(function() {
  var input = document.getElementById("vectorFilter");
  var counter = document.getElementById("vectorFilterCount");
  if (!input) return;

  var blocks = Array.prototype.slice.call(
    document.querySelectorAll(".category-block")
  );

  function totalVectors() {
    var n = 0;
    blocks.forEach(function(b) {
      n += b.querySelectorAll(".vector-card").length;
    });
    return n;
  }

  function updateCounter(visible) {
    if (!counter) return;
    counter.textContent = visible + " / " + totalVectors() + " vectors";
  }

  function applyFilter() {
    var q = input.value.trim().toLowerCase();
    var visible = 0;
    blocks.forEach(function(block) {
      var anyVisible = false;
      var cards = block.querySelectorAll(".vector-card");
      cards.forEach(function(card) {
        var hay = card.textContent.toLowerCase();
        var show = !q || hay.indexOf(q) !== -1;
        card.style.display = show ? "" : "none";
        if (show) { anyVisible = true; visible++; }
      });
      block.style.display = anyVisible ? "" : "none";
    });
    updateCounter(visible);
  }

  updateCounter(totalVectors());
  input.addEventListener("input", applyFilter);
})();
"""


def build_html(
    recon: NormalizedRecon,
    summary: PTAssessmentSummary,
    mapping: list[OwaspMappingItem],
    assignments: list[PTTestAssignment],
    vectors: list[AttackVector],
) -> str:
    """Render a self-contained PT HTML dashboard."""
    caps = recon.capabilities

    # ---- Metric chips ----
    p_counts: dict[str, int] = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0}
    for m in mapping:
        if m.applicable and m.priority in p_counts:
            p_counts[m.priority] += 1
    applicable_count = sum(1 for m in mapping if m.applicable)

    metric_chips: list[tuple[str, str, str]] = [
        ("", str(applicable_count), "Applicable"),
        ("", str(len(vectors)), "Vectors"),
        ("sev-critical", str(p_counts["Critical"]), "Critical"),
        ("sev-high", str(p_counts["High"]), "High"),
        ("sev-medium", str(p_counts["Medium"]), "Medium"),
        ("sev-low", str(p_counts["Low"]), "Low"),
        ("", str(len(assignments)), "Assignments"),
    ]
    metrics_html = "".join(
        f"<div class='metric'><div class='metric-num {extra}'>{num}</div>"
        f"<div class='metric-lbl'>{label}</div></div>"
        for extra, num, label in metric_chips
    )

    # ---- Target bar ----
    key_caps = [
        flag
        for flag, value in (
            ("has_tools", caps.has_tools),
            ("has_mcp", caps.has_mcp),
            ("has_memory", caps.has_memory),
            ("has_rag", caps.has_rag),
            ("can_execute_code", caps.can_execute_code),
            ("can_call_external_apis", caps.can_call_external_apis),
            ("can_modify_data", caps.can_modify_data),
            ("multi_agent", caps.multi_agent),
            ("has_human_approval", caps.has_human_approval),
        )
        if value
    ]
    key_caps_html = (
        "".join(
            f'<span class="badge type-badge">{_html_escape(k)}</span>' for k in key_caps
        )
        or '<span class="muted">none confirmed</span>'
    )

    focus_html = (
        "".join(f"<li>{_html_escape(f)}</li>" for f in summary.top_focus_areas)
        or '<li class="muted">none</li>'
    )

    # ---- Sections ----
    owasp_table_html = _render_owasp_table(mapping)
    owasp_cards_html = _render_owasp_cards(mapping)
    vectors_html = _render_vectors_section(mapping, vectors)
    assignments_html = _render_assignments(assignments)

    overall_class = _priority_class(summary.overall_risk)

    title = _html_escape(
        f"AI Agent PT Plan - {summary.target_name}"
    )

    parts: list[str] = []
    parts.append("<!doctype html>")
    parts.append('<html lang="en" data-theme="dark"><head>')
    parts.append('<meta charset="utf-8">')
    parts.append('<meta name="viewport" content="width=device-width, initial-scale=1">')
    parts.append(f"<title>{title}</title>")
    parts.append(f"<style>{_HTML_CSS}\n{_PT_EXTRA_CSS}</style>")
    parts.append("</head><body><div class='container'>")

    # Header
    parts.append(
        "<header class='app-header'>"
        "<div>"
        "<h1><span class='logo'>PT</span> AI Agent Penetration Testing Plan "
        f"<span class='pill {overall_class}'>{_html_escape(summary.overall_risk)}</span></h1>"
        f"<div class='subtitle'>Target: <strong>{_html_escape(summary.target_name)}</strong>"
        f" &middot; type: <code>{_html_escape(summary.target_type)}</code></div>"
        "</div>"
        "<div class='actions'>"
        "<button class='btn' id='themeBtn' type='button' title='Toggle theme'>Theme</button>"
        "<button class='btn' id='printBtn' type='button' title='Print or save as PDF'>Print</button>"
        "</div>"
        "</header>"
    )

    # TOC
    parts.append(
        "<nav class='toc' aria-label='Sections'>"
        "<a href='#summary'>Summary</a>"
        "<a href='#owasp-map'>OWASP Mapping</a>"
        "<a href='#vectors'>Attack Vectors</a>"
        "<a href='#plan'>Test Plan</a>"
        "<a href='#notes'>Execution Notes</a>"
        "</nav>"
    )

    # Target bar
    parts.append(
        "<div class='target-bar'>"
        f"<div class='kv'><span class='k'>Target</span>"
        f"<span class='v'>{_html_escape(summary.target_name)}</span></div>"
        f"<div class='kv'><span class='k'>Type</span>"
        f"<span class='v'>{_html_escape(summary.target_type)}</span></div>"
        f"<div class='kv'><span class='k'>Identity model</span>"
        f"<span class='v'>{_html_escape(caps.identity_model)}</span></div>"
        f"<div class='kv'><span class='k'>Permission scope</span>"
        f"<span class='v'>{_html_escape(caps.permission_scope)}</span></div>"
        "</div>"
    )

    # Metrics
    parts.append(f"<div class='metrics'>{metrics_html}</div>")

    # Summary
    parts.append(
        "<section class='card' id='summary'>"
        "<h2>Assessment Summary</h2>"
        f"<p>{_html_escape(summary.reason) or '<span class=&quot;muted&quot;>(no summary)</span>'}</p>"
        "<h4 class='muted small' style='margin:14px 0 6px'>Key capabilities</h4>"
        f"<div>{key_caps_html}</div>"
        "<h4 class='muted small' style='margin:14px 0 6px'>Top focus areas</h4>"
        f"<ol class='recs'>{focus_html}</ol>"
        "</section>"
    )

    # OWASP mapping
    parts.append(
        "<section class='card' id='owasp-map'>"
        "<h2>OWASP Agentic AI Mapping</h2>"
        "<p class='muted small'>Reference: "
        "<code>promptfoo.dev/docs/red-team/owasp-agentic-ai/</code></p>"
        f"{owasp_table_html}"
        "<h4 class='muted small' style='margin:18px 0 8px'>Applicable categories</h4>"
        f"{owasp_cards_html}"
        "</section>"
    )

    # Vectors
    parts.append(
        "<section class='card' id='vectors'>"
        "<h2>Prioritized Attack Vectors</h2>"
        f"{vectors_html}"
        "</section>"
    )

    # Test plan
    parts.append(
        "<section class='card' id='plan'>"
        "<h2>PT Test Plan</h2>"
        f"{assignments_html}"
        "</section>"
    )

    # Execution notes
    parts.append(
        "<section class='card' id='notes'>"
        "<h2>Execution Notes</h2>"
        "<ul>"
        "<li><strong>Scope.</strong> Only the target identified above, only the "
        "capabilities listed in this report, and only in the engagement-approved "
        "environment.</li>"
        "<li><strong>Safe testing rules.</strong> Every vector is non-destructive. "
        "Use only the marker <code>PT_TEST_TOKEN_DO_NOT_EXECUTE</code>, safe "
        "commands (<code>whoami</code>, <code>hostname</code>), test recipients, "
        "and dry-run modes. Do NOT escalate beyond the documented steps.</li>"
        "<li><strong>Required approvals.</strong> Confirm written authorization to "
        "assess the target before execution.</li>"
        "<li><strong>Logging and evidence.</strong> Capture full request/response "
        "bodies, tool-call traces, authorization decisions, and timestamps. "
        "Preserve session ids.</li>"
        "<li><strong>Backout / rollback.</strong> For data-modification vectors, "
        "use isolated test records only and restore state immediately after each "
        "test.</li>"
        "</ul>"
        "</section>"
    )

    parts.append(
        "<div class='disclaimer'>"
        "<strong>Authorized-use disclaimer.</strong> This plan was generated by "
        "<code>ai-agent-recon</code> Phase 2-4. The plan contains test descriptions "
        "only - no destructive payloads. Use only against systems you own or are "
        "explicitly authorized to assess."
        "</div>"
    )
    parts.append("<footer>Generated by ai-agent-recon &middot; PT planning crew</footer>")
    parts.append("</div>")
    parts.append(f"<script>{_HTML_JS}\n{_PT_JS}</script>")
    parts.append("</body></html>")
    return "".join(parts)


# ---------------------------------------------------------------------------
# Output writer
# ---------------------------------------------------------------------------

def _dump(obj, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        if hasattr(obj, "model_dump"):
            json.dump(obj.model_dump(mode="json"), f, indent=2, ensure_ascii=False)
        else:
            json.dump(obj, f, indent=2, ensure_ascii=False, default=str)
    return path


def write_pt_outputs(
    output_dir: str | Path,
    recon: NormalizedRecon,
    mapping: list[OwaspMappingItem],
    summary: PTAssessmentSummary,
    assignments: list[PTTestAssignment],
    vectors: list[AttackVector],
) -> list[Path]:
    """Write the six canonical files into ``output_dir`` and return their paths."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    paths: list[Path] = []
    paths.append(_dump(recon, out / "normalized-recon.json"))

    paths.append(
        _dump(
            {"owasp_mapping": [m.model_dump(mode="json") for m in mapping]},
            out / "owasp-mapping.json",
        )
    )

    paths.append(
        _dump(
            {
                "assessment_summary": summary.model_dump(mode="json"),
                "pt_test_plan": [a.model_dump(mode="json") for a in assignments],
            },
            out / "pt-test-plan.json",
        )
    )

    paths.append(
        _dump(
            {"attack_vectors": [v.model_dump(mode="json") for v in vectors]},
            out / "attack-vectors.json",
        )
    )

    md = build_markdown(recon, summary, mapping, assignments, vectors)
    md_path = out / "report.md"
    md_path.write_text(md, encoding="utf-8")
    paths.append(md_path)

    html = build_html(recon, summary, mapping, assignments, vectors)
    html_path = out / "report.html"
    html_path.write_text(html, encoding="utf-8")
    paths.append(html_path)

    return paths


def build_full_plan(
    recon: NormalizedRecon,
    mapping: list[OwaspMappingItem],
    summary: PTAssessmentSummary,
    assignments: list[PTTestAssignment],
    vectors: list[AttackVector],
) -> PTPlan:
    """Bundle everything into a single :class:`PTPlan` object."""
    return PTPlan(
        assessment_summary=summary,
        owasp_mapping=mapping,
        pt_test_plan=assignments,
        attack_vectors=vectors,
    )
